server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hand_test?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
    initialSize: 5
    maxWait: 60000
    maxActive: 20
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  #国际化支持
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: config/i18n/messages
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-seconds: 3600
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql
mybatis:
  typeAliasesPackage: com.cloudhelios.atlantis.domain
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config:
    classpath: logback-spring.xml
liquibase:
  change-log: classpath:config/liquibase/master.xml
lucene:
  path: ./lucene



